---
- name: RedHat - Asegurar que Java esta instalado
  yum: name={{ jenkins_java_version }} state=present
  when: ansible_os_family == 'RedHat' 

- name: Comprobar que jenkins_init_file existe
  stat:
    path: "{{ jenkins_init_file }}"
  register: jenkins_init_file_stat

- name: Comprobar que jenkins_init_file existe y modificar permisos
  file:
    path: "{{ jenkins_init_file }}"
    state: touch
    mode: 0644
  when: not jenkins_init_file_stat.stat.exists

- name: Modificar variables en el fichero init
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^{{ item.option }}='
    regexp: '^{{ item.option }}=\"\${{ item.option }} '
    line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
    state: present
    mode: 0644
  with_items: "{{ jenkins_init_changes }}"
  register: jenkins_init_prefix

- name: Comprobar que jenkins_home {{ jenkins_home }} existe
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: u+rwx
    follow: true

- name: Definir el directorio Jenkins home
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    regexp: '^JENKINS_HOME=.*'
    line: 'JENKINS_HOME={{ jenkins_home }}'
    mode: 0644
  register: jenkins_home_config

- name: Restart inmediato si hay cambios en la configuracion inicial de Jenkins
  service: name=jenkins state=restarted
  when: jenkins_init_prefix.changed
  tags: ['skip_ansible_lint']

- name:  Definir el puerto HTTP de Jenkins
  lineinfile:
    backrefs: true
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port_param }}='
    line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
    mode: 0644
  register: jenkins_http_config

- name: Crear el directorio custom inicial de scripts
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Activar los disparadores de los handlers en caso de que Jenkins este instalado
  meta: flush_handlers

- name: Restart de Jenkins si hay cambios http o del usuario
  service: name=jenkins state=restarted
  when: >
    (jenkins_users_config is defined and jenkins_users_config.changed)
    or (jenkins_http_config is defined and jenkins_http_config.changed)
    or (jenkins_home_config is defined and jenkins_home_config.changed)
  tags: ['skip_ansible_lint']
